version: '3'
services:
  redis_db:
    image: 'redis'
    container_name: DATABASE_REDIS_DNS_NAME
  backend_server:
    build: 
      context: ./backend
    ports:
      - "8080:8080"     
    container_name: BACKEND_DNS_NAME
  frontend_server:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"     
    container_name: FRONTEND_DNS_NAME
    stdin_open: true
