version: '3'
services:

  redis_db:
    image: 'redis'
    container_name: DATABASE_REDIS_DNS_NAME
    volumes:
      - redis_volume:/data

  postgres_db:
    image: postgres
    container_name: DATABASE_POSTGRES_DNS_NAME
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  backend_server:
    build: 
      context: ./backend
    ports:
      - "8080:8080"     
    container_name: BACKEND_DNS_NAME
    depends_on:
      - redis_db
      - postgres_db

  frontend_server:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"     
    container_name: FRONTEND_DNS_NAME
    stdin_open: true
    depends_on:
      - backend_server
    
  nginx_web_server_proxy:
    build:
      context: ./proxy
    ports:
      - 8081:80
    container_name: PROXY_DNS_NAME
    depends_on:
      - backend_server
      - frontend_server

volumes:
  postgres_volume:
  redis_volume:
