version: '3'
services:
  redis_db:
    image: 'redis'
    container_name: DATABASE_REDIS_DNS_NAME
  backend_server:
    build: 
      context: ./backend
    ports:
      - "8080:8080"     
    container_name: BACKEND_DNS_NAME
