version: '3'
services:

  redis_db:
    build:
      context: ./redis_db
      dockerfile: Dockerfile
    image: redis_image
    container_name: DATABASE_REDIS_DNS_NAME
    volumes:
      - redis_volume:/data

  postgres_db:
    build:
      context: ./postgres_db
      dockerfile: Dockerfile
    image: postgres_image
    container_name: DATABASE_POSTGRES_DNS_NAME
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  backend_server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend_image
    container_name: BACKEND_DNS_NAME
    restart: on-failure
    ports:
      - "8080:8080"     
    depends_on:
      - redis_db
      - postgres_db

  frontend_server:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend_image
    container_name: FRONTEND_DNS_NAME
    ports:
      - "3000:3000"     
    stdin_open: true
    depends_on:
      - backend_server
    
volumes:
  postgres_volume:
  redis_volume:
